name: issue-status-sample

on:
  issue_comment:
    types: [created]

jobs:
  issue-comment:
    runs-on: ubuntu-18.04
    steps:
      - uses: bryanmacfarlane/issue-status-labeler@main
        with:
          labels: green, yellow, red
          colors: 22a524, fbca04, b60205
