name: tools

on:
  push:
    paths:
    - 'samples/tools.md'
    - '.github/workflows/tools.yml'

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: tool-cache
        run: |
          echo RUNNER_TOOL_CACHE: ${RUNNER_TOOL_CACHE}
          echo TOOLS_DIRECTORY: ${RUNNER_TOOLSDIRECTORY}
      - name: go info
        run: |
          echo go installed at $(which go)
          echo go version: $(go version)
          echo go env GOPATH: $(go env GOPATH)
          echo go versions in tool cache: 
          echo $(ls $RUNNER_TOOL_CACHE/go)
      - name: setup-go
        uses: actions/setup-go@v2-beta
        with:
          go-version: '^1.13.1'
      - name: go info
        run: |
          echo go installed at $(which go)
          echo go version: $(go version)
          echo go env GOPATH: $(go env GOPATH)
          echo go versions in tool cache: 
          echo $(ls $RUNNER_TOOL_CACHE/go) 
      - name: path
        shell: bash
        run: echo PATH       
